# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
sudo: false
cache: packages

before_install:
  - Rscript -e 'install.packages("rapidjsonr")'

after_success:
  - Rscript -e 'covr::codecov()'
