# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_df_to_geojson_atomise <- function(df, geometry_columns, digits, factors_as_string) {
    .Call(`_geojsonsf_rcpp_df_to_geojson_atomise`, df, geometry_columns, digits, factors_as_string)
}

rcpp_df_to_geojson <- function(df, geometry_columns, digits, factors_as_string) {
    .Call(`_geojsonsf_rcpp_df_to_geojson`, df, geometry_columns, digits, factors_as_string)
}

rcpp_geojson_to_sfc <- function(geojson, expand_geometries) {
    .Call(`_geojsonsf_rcpp_geojson_to_sfc`, geojson, expand_geometries)
}

rcpp_geojson_to_sf <- function(geojson, expand_geometries) {
    .Call(`_geojsonsf_rcpp_geojson_to_sf`, geojson, expand_geometries)
}

rcpp_geojson_to_wkt <- function(geojson) {
    .Call(`_geojsonsf_rcpp_geojson_to_wkt`, geojson)
}

rcpp_read_sfc_file <- function(file, flatten_geometries) {
    .Call(`_geojsonsf_rcpp_read_sfc_file`, file, flatten_geometries)
}

rcpp_read_sf_file <- function(file, flatten_geometries) {
    .Call(`_geojsonsf_rcpp_read_sf_file`, file, flatten_geometries)
}

rcpp_sfc_to_geojson <- function(sfc, digits) {
    .Call(`_geojsonsf_rcpp_sfc_to_geojson`, sfc, digits)
}

rcpp_sf_to_geojson_atomise <- function(sf, digits, factors_as_string) {
    .Call(`_geojsonsf_rcpp_sf_to_geojson_atomise`, sf, digits, factors_as_string)
}

rcpp_sf_to_geojson <- function(sf, digits, factors_as_string) {
    .Call(`_geojsonsf_rcpp_sf_to_geojson`, sf, digits, factors_as_string)
}

